name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "30 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: f4df2a9b82cfdec1177c795b8ed2a2d3
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
